name: audio_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - ipywidgets
  - fluidsynth
  - libsndfile
  - portaudio
  - pip
  - pip:
      - torch --extra-index-url https://download.pytorch.org/whl/cu121
      - numpy
      - transformers
      - scipy
      - matplotlib
      - tqdm
      - music21
      - muspy
      - pretty-midi
      - mido
      - pypianoroll
      - miditoolkit
      - wandb
      - python-dotenv
      - peft